### ISSUE TITLE
auditd check has duplicates

### ISSUE THREAD

**Issue by TheFlipside** [hardenedlinux/harbian-audit#15]
Note the following expressions which are checked to be present in the auditd rules configuration:

**-a always,exit -F path=/usr/lib/openssh/ssh-keysign -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/ssh-agent -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/ssh-agent -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/chage -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/newgrp -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged**

The same expressions are checked by other scripts in the auditd section.
Only the "-k" flag differs, e.g. -k privileged-ssh, -k privileged-passwd, -k privileged-priv_change, -k privileged-cron
Applying all recommendations would mean overloading the auditd rules configuration with duplicates, leading to an unoptimized system.
I recommend removing the listed expressions from "/harbian-audit/bin/hardening/8.1.12_record_privileged_commands.sh" as they are covered by other checks already.

**Comment by Samson-W** [comment]
Thank you very much for your report on this bug.
Here are the details of the fix: 
Renamed the original 8.1.12 to 8.1.31 and executed it at the end of the audit rule related items, to check whether there is a duplicate. If a rule with the same file name already exists before, the rule will not be added.

**Comment by TheFlipside** [comment]
Hello,
something must be missing when the changes were made; when the test is run now the following output repeats itself a lot of times:

**harbian-audit/bin/hardening/8.1.31_record_privileged_commands.sh: line 31: AUDITRULE: unbound variable**
