### ISSUE TITLE
sshd parameters flagged poorly

### ISSUE THREAD

**Issue by prensing** [hardenedlinux/harbian-audit#21]
First, really appreciate the scripts. Hard to get tools that actually work.

The way the scripts check settings for SSHD should be improved. The default parameters are mostly correct, but the scripts flag them as "not set". The script should use "sshd -T" to check the value of settings, instead of directly grepping /etc/ssh/sshd_config. This would probably clear up most problems in a default install.

**Comment by Samson-W** [comment]
First, thank you very much for your report on this bug. This bug has been fixed.
Fixed in [fad60e5](https://github.com/hardenedlinux/harbian-audit/commit/fad60e595beed00443bcb2060aa9d981f6b3ff1a)
