### ISSUE TITLE
need extra checks on audisp path on Ubuntu

### ISSUE THREAD

**Issue by citypw** [hardenedlinux/harbian-audit#37]
Ubuntu has different path of audisp: 

/etc/audit/audisp-remote.conf

Please fix it in 8.1.1.5_ensure_set_remote_server.sh

**Comment by Samson-W** [comment]
bin/hardening.sh: Add Ubuntu init

Add check /etc/audit/audisp-remote.conf for Ubuntu: 
8.1.1.5_ensure_set_remote_server.sh
8.1.1.6_ensure_set_encrypt_for_audit_remote.sh
8.1.1.7_ensure_set_action_for_audit_storage_full.sh
8.1.1.8_ensure_set_action_for_net_fail.sh 
8.1.27_record_Events_that_modify_conf_files.sh
