### ISSUE TITLE
10.1.1 and 10.1.2 checks fail even when they should pass

### ISSUE THREAD

**Issue by Routhinator** [hardenedlinux/harbian-audit#41]
Checks 10.1.1 and 10.1.2 both fail in spite of the following being present in login.defs:

```
PASS_MAX_DAYS 60
PASS_MIN_DAYS 1
```
Output
```shell
hardening                 [INFO] Treating /root/harbian-audit/bin/hardening/10.1.1_set_password_exp_days.sh
10.1.1_set_password_exp_d [INFO] Working on 10.1.1_set_password_exp_days
10.1.1_set_password_exp_d [INFO] Checking Configuration
10.1.1_set_password_exp_d [INFO] Performing audit
10.1.1_set_password_exp_d [ OK ] ^PASS_MAX_DAYS[[:space:]]*60 is present in /etc/login.defs
10.1.1_set_password_exp_d [ KO ] Have least user's maxinum password lifttime is greater than 60 day
10.1.1_set_password_exp_d [ KO ] Check Failed
hardening                 [INFO] Treating /root/harbian-audit/bin/hardening/10.1.2_set_password_min_days_change.sh
10.1.2_set_password_min_d [INFO] Working on 10.1.2_set_password_min_days_change
10.1.2_set_password_min_d [INFO] Checking Configuration
10.1.2_set_password_min_d [INFO] Performing audit
10.1.2_set_password_min_d [ OK ] ^PASS_MIN_DAYS[[:space:]]*1 is present in /etc/login.defs
10.1.2_set_password_min_d [ KO ] Have least user's mininum password lifttime is not equal or less than 1 day
10.1.2_set_password_min_d [ KO ] Check Failed

```

**Comment by Routhinator** [comment]
Same problem with 9.3.25:

In sshd_config:
```
LoginGraceTime 60
```

Yet it fails:
```
9.3.25_sshd_logingracetim [ OK ] openssh-server is installed
9.3.25_sshd_logingracetim [ KO ] The keyword value pair "LoginGraceTime 60" does not exist in the sshd runtime configuration.
9.3.25_sshd_logingracetim [ KO ] LoginGraceTime 60 is not present in /etc/ssh/sshd_config
9.3.25_sshd_logingracetim [ KO ] Check Failed

```

**Comment by Routhinator** [comment]
Same with 9.3.20 - once again the setting is exactly as it should be but the check fails.

```
9.3.20_sshd_compression   [ OK ] openssh-server is installed
9.3.20_sshd_compression   [ KO ] The keyword value pair "Compression no" does not exist in the sshd runtime configuration.
9.3.20_sshd_compression   [ KO ] The value of keyword Compression is not set to no, it's incorrect.
9.3.20_sshd_compression   [ KO ] Check Failed

```

**Comment by Samson-W** [comment]
> ```shell
> /etc/login.defs
> ```



> Checks 10.1.1 and 10.1.2 both fail in spite of the following being present in login.defs:
> 
> ```
> PASS_MAX_DAYS 60
> PASS_MIN_DAYS 1
> ```
> 
> Output
> 
> ```shell
> hardening                 [INFO] Treating /root/harbian-audit/bin/hardening/10.1.1_set_password_exp_days.sh
> 10.1.1_set_password_exp_d [INFO] Working on 10.1.1_set_password_exp_days
> 10.1.1_set_password_exp_d [INFO] Checking Configuration
> 10.1.1_set_password_exp_d [INFO] Performing audit
> 10.1.1_set_password_exp_d [ OK ] ^PASS_MAX_DAYS[[:space:]]*60 is present in /etc/login.defs
> 10.1.1_set_password_exp_d [ KO ] Have least user's maxinum password lifttime is greater than 60 day
> 10.1.1_set_password_exp_d [ KO ] Check Failed
> hardening                 [INFO] Treating /root/harbian-audit/bin/hardening/10.1.2_set_password_min_days_change.sh
> 10.1.2_set_password_min_d [INFO] Working on 10.1.2_set_password_min_days_change
> 10.1.2_set_password_min_d [INFO] Checking Configuration
> 10.1.2_set_password_min_d [INFO] Performing audit
> 10.1.2_set_password_min_d [ OK ] ^PASS_MIN_DAYS[[:space:]]*1 is present in /etc/login.defs
> 10.1.2_set_password_min_d [ KO ] Have least user's mininum password lifttime is not equal or less than 1 day
> 10.1.2_set_password_min_d [ KO ] Check Failed
> ```

The passing of this item is not just checking /etc/login.defs, /etc/login.defs does not work for the created user, the reason for the failure is that the corresponding configuration of the existing user does not conform to the rules.

Please use the following command to confirm:
10.1.1:
```
sudo egrep '^[^:]+:[^!*]' /etc/shadow  | awk -F: '$5 > "60" {print $1}'
```
10.1.2:
```
sudo egrep '^[^:]+:[^!*]' /etc/shadow | awk -F: '$4 < "1" {print $1}'
```

**Comment by Samson-W** [comment]
> Same problem with 9.3.25:
> 
> In sshd_config:
> 
> ```
> LoginGraceTime 60
> ```
> 
> Yet it fails:
> 
> ```
> 9.3.25_sshd_logingracetim [ OK ] openssh-server is installed
> 9.3.25_sshd_logingracetim [ KO ] The keyword value pair "LoginGraceTime 60" does not exist in the sshd runtime configuration.
> 9.3.25_sshd_logingracetim [ KO ] LoginGraceTime 60 is not present in /etc/ssh/sshd_config
> 9.3.25_sshd_logingracetim [ KO ] Check Failed
> ```

This error is not found in Debian 11 or UBUNTU 22.04. Please check whether the path of the sshd_config file is /etc/ssh/sshd_config.

**Comment by Samson-W** [comment]
> Same with 9.3.20 - once again the setting is exactly as it should be but the check fails.
> 
> ```
> 9.3.20_sshd_compression   [ OK ] openssh-server is installed
> 9.3.20_sshd_compression   [ KO ] The keyword value pair "Compression no" does not exist in the sshd runtime configuration.
> 9.3.20_sshd_compression   [ KO ] The value of keyword Compression is not set to no, it's incorrect.
> 9.3.20_sshd_compression   [ KO ] Check Failed
> ```

This error is not found in Debian 11 or UBUNTU 22.04. Please check whether the path of the sshd_config file is /etc/ssh/sshd_config.
Whether the first line of the configuration line contains spaces, the configuration line must meet the following rules:
```
grep "^Compression" /etc/ssh/sshd_config
```

**Comment by Routhinator** [comment]
Results from your commands:

```
$ sudo egrep '^[^:]+:[^!*]' /etc/shadow  | awk -F: '$5 > "60" {print $1}'
root
$ sudo egrep '^[^:]+:[^!*]' /etc/shadow | awk -F: '$4 < "1" {print $1}'
root
$ sudo grep "^Compression" /etc/ssh/sshd_config
Compression no
```

What was the expected output?

**Comment by Routhinator** [comment]
9.* are passing now, however the 10.* checks are still failing.

**Comment by Routhinator** [comment]
Realized that the line for root in shadow needed modification.
